# Generated by Django 4.2.13 on 2024-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('nickname', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('0', '男'), ('1', '女')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
