# Generated by Django 4.2.13 on 2024-06-16 18:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consumer_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant_logos/')),
                ('description', ckeditor.fields.RichTextField()),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
                ('establishment_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('bank_account_info', models.TextField(blank=True)),
            ],
        ),
    ]
