# Generated by Django 4.2.13 on 2024-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_shoppingcart_shoppingcartproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
