# Generated by Django 4.2.13 on 2024-06-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_shoppingcartitem_shoppingcart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='products',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='shoppingcart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.shoppingcart'),
        ),
        migrations.DeleteModel(
            name='ShoppingCartProduct',
        ),
    ]
