# Generated by Django 4.2.13 on 2024-06-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_city_address_destination_remove_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='consumer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='merchant',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
