# Generated by Django 4.2.13 on 2024-06-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_consumer_password_consumer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
